USE WildlifeDB;

-- 1) List all endangered species
SELECT Name, Category, Status FROM Species WHERE Status = 'Endangered';

-- 2) Show all sightings with details (using the view)
SELECT * FROM sighting_report;

-- 3) Show all alerts generated by the trigger
SELECT * FROM Alerts;

-- 4) Most sighted species (with total count)
SELECT s.Name, SUM(si.Quantity) AS Total_Sighted
FROM Sightings si
JOIN Species s ON si.SpeciesID = s.SpeciesID
GROUP BY s.Name
ORDER BY Total_Sighted DESC;

-- 5) Most sighted species by location
SELECT l.LocationName, s.Name, SUM(si.Quantity) AS Total_Sighted
FROM Sightings si
JOIN Species s ON si.SpeciesID = s.SpeciesID
JOIN Locations l ON si.LocationID = l.LocationID
GROUP BY l.LocationName, s.Name
ORDER BY l.LocationName, Total_Sighted DESC;

-- 6) Get sightings of a species using procedure
CALL get_sightings_by_species('Bengal Tiger');

-- 7) Show sightings in a date range
SELECT * FROM sighting_report
WHERE DateSeen BETWEEN '2025-07-01' AND '2025-09-30';
